### ISSUE TITLE
Does `config.json` accept ENV values?

### ISSUE THREAD

**Issue by gjtorikian** [jamesmartin/underway#8]
For example, Heroku apps often set their URL to [`ENV['DATABASE_URL']`](https://devcenter.heroku.com/articles/heroku-postgresql#provisioning-heroku-postgres), and

> The value of your app’s `DATABASE_URL` config var might change at any time. You should not rely on this value either inside or outside your Heroku app.

I'm curious to know if the value for `database_url ` can be set  to something dynamic? And if that's not accepted, would a PR allowing that be accepted?

**Comment by gjtorikian** [comment]
Boop @jamesmartin.

**Comment by jamesmartin** [comment]
Sorry for the delayed response. Right now, all of the configuration values, including `database_url`, are static. 

> And if that's not accepted, would a PR allowing that be accepted?

Yep. Sounds good to me 👍

**Comment by jamesmartin** [comment]
I finally used this gem in a context that needed configuration variables from `ENV`, so it's now possible to set the `database_url` in the configure block:

```ruby
Underway::Settings.configure do |config|
  # other settings here…
  config.database_url = "/some/url/for/my/db"
end
```
